Adding the ChartLabelSettings and auxiliary classes to allow specifying the labels for a chart. -- Importing Chart in the right way so that chart.component.d.ts has no compile "error TS2304: Cannot find name 'Chart'"